services:
  m7toolbox:
    build: .
    ports:
      - "3007:3000"
    restart: unless-stopped
    environment:
      - NEXTAUTH_SECRET=m7toolbox-super-secret-key-change-in-production-2024
      - NEXTAUTH_URL=http://localhost:3007
      - DATABASE_URL=file:./prisma/dev.db
